version: "3.9"
services:
  express-api:
    container_name: express-api-container
    image: express-api-server:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
    ports:
      - "3000:80"
