env:
  node: true
  es2022: true
extends:
  - eslint:recommended
  - prettier # Prettierと競合しないようにする
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: "@typescript-eslint/parser" # TypeScriptコードを扱えるようにする設定
parserOptions:
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
rules: # 独自ルール
  "@typescript-eslint/no-unsafe-argument": "warn"
  "@typescript-eslint/no-unsafe-assignment": "warn"
  "@typescript-eslint/restrict-plus-operands": "warn"
  "@typescript-eslint/no-unsafe-return": "warn"
  "@typescript-eslint/no-unsafe-member-access": "warn"
  "@typescript-eslint/no-unused-vars": "warn"
root: true # 本設定ファイルをESLintの最上位の設定ファイルとする
ignorePatterns: # ESLintで無視するディレクトリ
  - "dist/**/*"
