version: "3.9"
services:
  websocket:
    container_name: websocket-container
    image: 622838898203.dkr.ecr.ap-northeast-1.amazonaws.com/websocket-server:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
    ports:
      - "80:80"
    tty: true
